const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('tabbin', {
  list: () => ipcRenderer.invoke('notes:list'),
  get: id => ipcRenderer.invoke('notes:get', id),
  create: () => ipcRenderer.invoke('notes:create'),
  update: note => ipcRenderer.invoke('notes:update', note),
  reorder: ids => ipcRenderer.invoke('notes:reorder', ids),
  remove: id => ipcRenderer.invoke('notes:delete', id),
  clear: confirm => ipcRenderer.invoke('notes:clear', confirm),
  setSaveLocation: dir => ipcRenderer.invoke('config:set', { saveLocation: dir }),
  pickFolder: () => ipcRenderer.invoke('dialog:browse-folder'),
  open: id => ipcRenderer.invoke('notes:open', id),
  hide: () => ipcRenderer.invoke('dock:hide'),
  cursorLeft: () => ipcRenderer.invoke('dock:cursor-left'),
  reportContentHeight: h => ipcRenderer.invoke('dock:content-height', h),
  quit: () => ipcRenderer.invoke('app:quit'),
  config: () => ipcRenderer.invoke('config:get'),
  setConfig: patch => ipcRenderer.invoke('config:set', patch),
  toggleNoteAlwaysOnTop: id => ipcRenderer.invoke('notes:toggle-always-on-top', id),
  updateStatus: () => ipcRenderer.invoke('updates:status'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  dismissUpdateNudge: () => ipcRenderer.invoke('updates:dismiss-nudge'),
  onChanged: callback => ipcRenderer.on('notes:changed', (_, notes) => callback(notes)),
  onConfigChanged: callback => ipcRenderer.on('config:changed', (_, config) => callback(config)),
  onUpdateState: callback => ipcRenderer.on('update:state', (_, state) => callback(state))
});
