const assert = require('assert');
const fs = require('fs');
const main = fs.readFileSync('main.js', 'utf8');
const dock = fs.readFileSync('dock.html', 'utf8');
const note = fs.readFileSync('note.html', 'utf8');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
assert.match(main, /ipcMain\.handle\('notes:reorder'/);
assert.match(main, /saveNotes\(\[\.\.\.ordered, \.\.\.remaining\]\)/);
assert.match(dock, /draggable=true/);
assert.match(dock, /window\.tabbin\.reorder\(notes\.map\(x=>x\.id\)\)/);
assert.match(dock, /background:transparent!important/);
assert.match(dock, /title="Hide dock">👁/);
assert.doesNotMatch(dock, /id="settings"/);
assert.doesNotMatch(dock, /id="pin"/);
assert.match(note, /contenteditable="true"/);
assert.match(note, /body::-webkit-scrollbar/);
assert.match(note, /\.editor::-webkit-scrollbar/);
assert.match(note, /title="Strikethrough" data-cmd="strikeThrough"/);
assert.match(note, /title="Numbered list" data-cmd="insertOrderedList"><svg/);
assert.match(note, /title="Bulleted list" data-cmd="insertUnorderedList"><svg/);
assert.match(note, /title="Align left"/);
assert.match(note, /title="Align center"/);
assert.match(note, /title="Align right"/);
assert.match(main, /resizable: true/);
assert.match(main, /window\.setResizable\(true\)/);
assert.match(main, /backgroundColor: noteColor/);
assert.match(main, /setBackgroundColor\(notes\[index\]\.color\)/);
assert.match(main, /notes:toggle-always-on-top/);
assert.match(note, /id="pinNote"/);
assert.match(note, /Always on top: off/);
assert.equal(pkg.build.productName, 'Tabbin');
assert.ok(!pkg.build.linux);
assert.match(pkg.build.nsis.include, /installer\.nsh/);
console.log('PASS: Tabbin rich-text, drag reorder, transparent dock, native-resizable notes, per-note pinning, and installer configuration');
